### ISSUE TITLE
Failed to link `libsndfile` on Windows

### ISSUE THREAD

**Issue by tuxzz** [evpobr/sndfile-sys#5]
https://travis-ci.org/github/Xeiron/sndfile.rs/jobs/671315289

I'm going to locate the problem.

**Comment by evpobr** [comment]
Hmm, is `libsndfile` package installed?

Also, `libsndfile` library on Windows is `libsndfile-1.dll`, not `sndfile.dll`.

**Comment by tuxzz** [comment]
This problem is caused by PR #1, sorry it's my fault.
On Windows+vcpkg, `#[link(name = "sndfile")]` should be removed.
PR is coming.
