### ISSUE TITLE
pkg-config changes needed on ARM Macs

### ISSUE THREAD

**Issue by irh** [evpobr/sndfile-sys#7]
Homebrew on ARM Macs now uses `/opt/homebrew/` instead of `/usr/local` as its default installation path. This causes builds with `sndfile` to fail as `libsndfile` can't be found outside of `/usr/local`.

The change to using `pkg-config` to search for libraries in e46f1a94e50d6f8fbb13f8a5148182ef3dae1c7d allows the library to be found as expected under `/opt/homebrew`, but I notice that it hasn't been published yet. Any chance of getting a release with this change?

Thanks for the handy library 🙏

**Comment by evpobr** [comment]
Thanks. Ok, I guess it is time to publish new release.

**Comment by evpobr** [comment]
Done!

**Comment by irh** [comment]
Great, thanks!
